### PR TITLE
Wallaby: Backport support for MS Teams alerting

### PR DESCRIPTION
**Pull request by cityofships**
Each backport had conflicts to be resolved.

### CODE REVIEW

**Review by mnasiadka — COMMENTED** [review]
MS Teams patch got merged in K-A yesterday, so safe for back porting. @priteau is the Jira one merged as well?

**Comment by cityofships** [comment]
I just noticed msteams is missing from 'Get container facts' precheck task

**Comment by priteau** [comment]
> MS Teams patch got merged in K-A yesterday, so safe for back porting. @priteau is the Jira one merged as well?

No, Jiralert hasn't been pushed upstream yet.

**Review by darmach — APPROVED** [review]

**Comment by priteau** [comment]
We will need to backport https://review.opendev.org/c/openstack/kolla-ansible/+/858270

**Pull request merged**
