### PR TITLE
Centos fluentd upgrade (Stein rebase)

### PR DESCRIPTION
**Pull request by Wasaac**
Upgrade fluentd to td-agent. Rebased onto latest stackhpc/stein.

### CODE REVIEW

**Comment by dougszumski** [comment]
I actually did this before and then abandoned it since it didn't fix the bug we had seen. It looks like there are a couple of extra commits (although I think you have the core of it here). Shall we re-open and merge below?

https://github.com/stackhpc/kolla-ansible/pull/103/commits

**Comment by Wasaac** [comment]
> I actually did this before and then abandoned it since it didn't fix the bug we had seen. It looks like there are a couple of extra commits (although I think you have the core of it here). Shall we re-open and merge below?
> 
> https://github.com/stackhpc/kolla-ansible/pull/103/commits

Good idea. Lets use yours.

**Comment by Wasaac** [comment]
Rebased @dougszumski 's #103 PR branch onto latest `stackhpc/stein` here and resolved merge conflicts.

**Comment by Wasaac** [comment]
Redundant - closing.

**Pull request closed without merging**
